CREATE TABLE IF NOT EXISTS qbank_generation_jobs (
    job_id VARCHAR(64) PRIMARY KEY,
    status VARCHAR(32) NOT NULL,
    selected_subject VARCHAR(255) NOT NULL,
    selected_chapter VARCHAR(255) NOT NULL,
    selected_input VARCHAR(255) NOT NULL,
    difficulty VARCHAR(32) NOT NULL,
    requested_count INT NOT NULL,
    requested_by VARCHAR(255) NOT NULL,
    resolved_topic_id INT NULL,
    resolved_subject_id INT NULL,
    resolved_chapter_id INT NULL,
    generated_count INT NOT NULL DEFAULT 0,
    passed_count INT NOT NULL DEFAULT 0,
    failed_count INT NOT NULL DEFAULT 0,
    input_tokens INT NOT NULL DEFAULT 0,
    output_tokens INT NOT NULL DEFAULT 0,
    total_tokens INT NOT NULL DEFAULT 0,
    retry_count INT NOT NULL DEFAULT 0,
    request_payload JSON NULL,
    error JSON NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    started_at DATETIME NULL,
    completed_at DATETIME NULL,
    published_at DATETIME NULL,
    INDEX idx_qbank_jobs_status (status),
    INDEX idx_qbank_jobs_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS qbank_generation_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL,
    question TEXT NOT NULL,
    options_json JSON NOT NULL,
    correct_answer TEXT NOT NULL,
    explanation TEXT NOT NULL,
    cognitive_level VARCHAR(64) NOT NULL,
    question_type VARCHAR(128) NOT NULL,
    estimated_time FLOAT NULL,
    concepts TEXT NULL,
    qc_status VARCHAR(16) NOT NULL,
    review_status VARCHAR(16) NOT NULL DEFAULT 'pending',
    scores_json JSON NULL,
    recommendations_json JSON NULL,
    violations_json JSON NULL,
    category_scores_json JSON NULL,
    raw_item_json JSON NULL,
    edited TINYINT(1) NOT NULL DEFAULT 0,
    published TINYINT(1) NOT NULL DEFAULT 0,
    published_question_id INT NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_qbank_items_job (job_id),
    INDEX idx_qbank_items_qc (qc_status),
    INDEX idx_qbank_items_review (review_status),
    INDEX idx_qbank_items_published (published)
);

CREATE TABLE IF NOT EXISTS qbank_job_events (
    id INT AUTO_INCREMENT PRIMARY KEY,
    job_id VARCHAR(64) NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    payload JSON NULL,
    created_at DATETIME NOT NULL,
    INDEX idx_qbank_events_job (job_id),
    INDEX idx_qbank_events_created_at (created_at)
);
