prompt = """
You are an expert AI assistant specializing in parsing and structuring academic documents. Your task is to meticulously extract information from a provided university syllabus document and convert it into a strictly structured JSON object.

You will be given the raw text content of a syllabus in the `content` variable.
You MUST generate a single, valid JSON object that conforms precisely to the provided `output_json` schema.

**Core Instructions:**

1.  **Accuracy and Completeness:**
    - Extract data verbatim from the `content` whenever possible.
    - You must populate EVERY field in the JSON schema. Do not omit any keys.

2.  **Handling Missing Data:**
    - If a specific piece of information (e.g., an author's name, a specific year, prerequisite) is genuinely not present in the source text, you MUST use the string "Not specified" as its value.
    - Do not use `null`, empty strings (`""`), or hallucinate (invent) information.

3.  **JSON Output Format:**
    - Your entire output must be a single, valid JSON object.
    - Do not include any explanatory text, markdown formatting (like ```json), or comments before or after the JSON object.

---

**Field-Specific Formatting Rules:**

- **`university`, `program`, `courseTitle`**: Extract these from the document header/title.
- **`syllabus_effective_from`**: Must be in the format "YYYY-YYYY" (e.g., "2023-2024").
- **`year`, `semester`**: Must be extracted as integers.
- **`subject_details.L, T, P, S, credits, instruction_hours`**: Extract as integers. If not specified, use 0.
- **`subject_details.marks`**: Extract the marks for CIA, external, and total as integers.

- **`units`**:
    - **CRITICAL**: Every unit object MUST contain ALL four required fields: `unit_number`, `title`, `content`, `hours_allocated`, and `topics`. Do NOT omit any field.
    - **`unit_number`**: Extract the unit number (1, 2, 3, etc.) as an integer. REQUIRED - never omit this.
    - **`title`**: REQUIRED - never omit this field.
        - Extract the descriptive title for the unit.
        - **Crucial Rule**: If a unit has a number (e.g., "UNIT I") but no descriptive title, you MUST infer a concise, descriptive title based on the unit's `content`.
        - *Example*: If the content is "Meaning- Definitions - Nature and Scope - Levels of Management...", a good inferred title would be "Introduction to Management".
    - **`content`**: REQUIRED - never omit this field. Extract the full descriptive content/topics covered in the unit as a single string. If no content is visible, use "Not specified".
    - **`topics`**: REQUIRED - must be an array. This array must be a detailed breakdown of the unit's `content`. Create a new string in the list for each distinct concept, definition, or sub-heading mentioned in the content paragraph. If no topics are visible, use an empty array [].
    - **`hours_allocated`**: Extract the number of hours for the unit as an integer. REQUIRED - use 0 if not specified.

- **`course_outcomes` (COs)**:
    - **CRITICAL**: Every course outcome object MUST contain ALL required fields: `CO`, `description`, and `programme_outcomes`. Do NOT omit any field.
    - **`CO`** (REQUIRED): The value for the `CO` key MUST be a string that includes the literal prefix "CO" followed by its number. For example: `"CO1"`, `"CO2"`, etc. **Do not simplify it to just the number like `"1"` or `1`.** This is a strict requirement.
    - **`description`** (REQUIRED): For each CO, extract its full description. If no description is available, use "Not specified".
    - **`programme_outcomes`** (REQUIRED - Array Rules):
        - **Source of Data**: This array MUST be generated by looking at the CO-PO mapping table in the syllabus.
        - **Inclusion Criteria**: Include a PO or PSO identifier in the list only if that PO/PSO has a mapping value (like a number 1, 2, 3, or a checkmark) for the corresponding CO row.
        - **Uniqueness Rule**: The array MUST contain a **unique list** of all `PO` and `PSO` identifiers that are mapped to that CO. **Do NOT repeat identifiers.**
        - If no programme outcomes are mapped, use an empty array [].
        - **Example**: If `CO1` maps to `PO1`, `PO2`, and `PSO1` in the mapping table, the array must be exactly `["PO1", "PO2", "PSO1"]`.
            
- **`mapping_with_programme_outcomes`**:
    - This section represents the CO-PO mapping matrix.
    - Parse the table that maps COs to POs and PSOs. The values should be integers (e.g., 3 for Strong, 2 for Medium, 1 for Low).
    - Map the summary row often labeled 'Weightage' or 'Total' to the `TOTAL` key in the JSON.
    - Map the summary row often labeled 'Weighted percentage of course contribution' or 'Average' to the `AVERAGE` key in the JSON.
    - **Strict Formatting**: Use the format 'PO1', 'PO2', 'PSO1', etc., with no spaces.

- **`textbooks` & `reference_books`**:
    - Extract each book as an object with `title`, `author`, `publisher`, `edition`, and `year`. Use "Not specified" for any missing details.

- **`question_paper_pattern`**:
    - Extract the entire description of the question paper format as a single string, preserving its structure.

- **`note`**:
    - Capture any final notes, especially the key for mapping levels (e.g., "S-Strong-3 M-Medium-2 L-Low-1").

---

Here is the document content:
"{content}"

Here is the target JSON structure. Fill it out completely based on the rules above.
{output_json}
"""

output_json={
  "university": "UNIVERSITY OF MADRAS",
  "program": "B.COM. (GENERAL) DEGREE PROGRAMME",
  "courseTitle": "B.COM. (GENERAL) DEGREE PROGRAMME",
  "syllabus_effective_from": "2023-2024",
  "year": 3,
  "semester": 5,
  "course": {
    "type": "core" or "elective" or "lab",
    "title": "BANKING LAW AND PRACTICE",
    "common_to": "BCom-AF, BM, CA, MM, ISM, Co-op. & CS"
  },
  "subject_details": {
    "subject_code": "346C5B",
    "L": 5,
    "T": 0,
    "P": 0,
    "S": 0,
    "credits": 4,
    "instruction_hours": 5,
    "marks": {
      "CIA": 25,
      "external": 75,
      "total": 100
    }
  },
  "learning_objectives": [
      {"LO": 1,"description":  "To help the students understand various provision of Banking Regulation Act 1949 applicable to banking companies including cooperative banks"},
      {"LO": 2,"description": "To trace the evolution of central bank concept and prevalent central banking system around the world and their roles and function"},
      {"LO": 3,"description": "To throw light on Central Bank in India, its formation, nationalizing its organization structure, role of bank to government, role in promoting agriculture and industry, role in financial inclusion"},
      {"LO": 4,"description": "To know the differentiation and its function"},
      {"LO": 5,"description": "To understand the second order derivatives and its maximin function"}
                          ],
  "course_outcomes": [
    {
      "CO": "CO1",
      "description": "Explain the importance and factors influencing entrepreneurship",
      "programme_outcomes": ["PO1", "PO2", "PO3"]
    },
    {
      "CO": "CO2",
      "description": "Understand and apply entrepreneurial theory using lean start-up principles. ",
      "programme_outcomes": ["PO1", "PO2"]
    },
    {
      "CO": "CO3",
      "description": "Analyse the Keynesian Underemployment Theory",
      "programme_outcomes": ["PO1", "PO2"]
    },
    {
      "CO": "CO4",
      "description": "Examine the theories of Consumption Function",
      "programme_outcomes": ["PO1", "PO2", "PO3"]
    },
    {
      "CO": "CO5",
      "description": "Understand the types and the impact of Inflation on Economies",
      "programme_outcomes": ["PO2", "PO3", "PO8"]
    }
  ],
  "units": [{ "unit_number": 1,
   "title": "Introduction to Management",
  "content": "Meaning- Definitions - Nature and Scope - Levels of Management - Importance - Management Vs. Administration - Management: Science or Art -Evolution of Management Thoughts - F. W. Taylor, Henry Fayol, Peter F. Drucker, Elton Mayo - Functions of Management - Trends and Challenges of Management. Managers - Qualification - Duties & Responsibilities.",
   "topics": ["Meaning of Management","Definitions of Management",
        "Nature and Scope of Management",
        "Levels of Management",
        "Importance of Management",
        "Management Vs. Administration",
        "Management: Science or Art",
        "Evolution of Management Thoughts (F. W. Taylor, Henry Fayol, Peter F. Drucker, Elton Mayo)",
        "Functions of Management",
        "Trends and Challenges of Management",
        "Managers (Qualification, Duties & Responsibilities)"
      ],
    "hours_allocated": 15
    },
    {
      "title": "Planning",
      "topics": [
        "Planning (Meaning, Definitions, Nature, Scope, Functions, Importance, Elements, Types, Process, Tools and Techniques, Management by Objective (MBO))",
        "Decision Making (Meaning, Characteristics, Types, Steps, Forecasting)"
      ],
      "content": "Planning - Meaning - Definitions - Nature - Scope and Functions - Importance and Elements of Planning - Types - Planning Process - Tools and Techniques of Planning - Management by Objective (MBO). Decision Making: Meaning - Characteristics - Types - Steps in Decision Making - Forecasting.",
      "unit_number": 2,
      "hours_allocated": 15
    },
  ],
  "total_hours": 75,
  "theory_vs_problems_ratio": {
    "theory": "20%",
    "problems": "80%"
  },
   "textbooks": [
    {
      "year": "",
      "title": "Principles of Management",
      "author": "Gupta.C.B, L.M. Prasad",
      "edition": "",
      "publisher": "S.Chand& Sons Co. Ltd"
    },
    {
      "year": "",
      "title": "Principles of Management",
      "author": "DinkarPagare",
      "edition": "",
      "publisher": "Sultan Chand & Sons Publications"
    }],
   "reference_books": [
    {
      "year": "",
      "title": "Principles Of Management",
      "author": "K Sundhar",
      "edition": "",
      "publisher": "Vijay Nichole Imprints Limited"
    },
    {
      "year": "",
      "title": "Essentials of Management",
      "author": "Harold Koontz, Heinz Weirich",
      "edition": "",
      "publisher": "McGraw Hill, Sultan Chand and Sons"
    }],
  "prerequisites": [
    "Should have studied Commerce in XII Std"
  ],
  "list_of_programs":["Formatting and editing a document",
                      "Saving and printing a given document",
                      "Use of page maker to make transparencies"],
  "web_resources": [
    "https://www.slideshare.net/mcsharma1/accounting-for-depreciation-1",
    "https://www.slideshare.net/ramusakha/basics-of-financial-accounting",
    "https://www.accountingtools.com/articles/what-is-a-single-entry-system.html"
  ],

  "mapping_with_programme_outcomes": {
    "CO1":     {
      "PO1": 3,
      "PO2": 2,
      "PO3": 3,
      "PSO1": 3,
      "PSO2": 2,
      "PSO3": 2
    },
    "CO2": {
      "PO1": 3,
      "PO2": 2,
      "PO3": 3,
      "PSO1": 3,
      "PSO2": 2,
      "PSO3": 2
    },
    "CO3": {
      "PO1": 3,
      "PO2": 2,
      "PO3": 3,
      "PSO1": 3,
      "PSO2": 2,
      "PSO3": 2
    },
    "CO4": {
      "PO1": 3,
      "PO2": 2,
      "PO3": 3,
      "PSO1": 3,
      "PSO2": 2,
      "PSO3": 2
    },
    "CO5": {
      "PO1": 3,
      "PO2": 2,
      "PO3": 3,
      "PSO1": 3,
      "PSO2": 2,
      "PSO3": 2
    },
    "TOTAL": {
      "PO1": 15,
      "PO2": 10,
      "PO3": 15,
      "PSO1": 15,
      "PSO2": 10,
      "PSO3": 10
    },
    "AVERAGE": {
      "PO1": 3,
      "PO2": 2,
      "PO3": 3,
      "PSO1": 3,
      "PSO2": 2,
      "PSO3": 2
    }
  },
  "question_paper_pattern": " Section A (10 x 2 = 20 Marks) ..... Section B (5 x 5 = 25 Marks).... ,",
  "note": "S-Strong-3 M-Medium-2  L-Low-1"
}



justification_prompt = """
You are an academic evaluator AI. Below is a list of Course Outcomes (COs) and Program Outcomes (POs) with mapping strengths (Strong/Medium/Low). For each CO-PO pair, generate a justification for how the CO maps to the PO at the specified strength.

List of mappings:
{mappings}

Program Outcome(Pos):{pos}

Cousre Outcomes(Cos):{co}

Provide json output format:
[
  {{
    "CO1": {{
      "PO1": "Justification text for CO1-PO1",
      "PO2": "Justification text for CO1-PO2"
    }}
  }},
  {{
    "CO2": {{
      "PO1": "Justification text for CO2-PO1"
    }}
  }}
  ... Continue for all COs
]
"""

extraction_prompt = """
You are an expert document formatter specializing in converting academic syllabi and course documents into well-structured markdown format. Follow these specific formatting guidelines:

### Document Structure

1. **Title**: Use single `#` for the main course title
2. **Major Sections**: Use `##` for primary sections (Course Information, Course Objectives, etc.)
3. **Sub-sections**: Use `###` for unit divisions and subsections
4. **Sub-sub-sections**: Use `####` for detailed breakdowns within units

### Table Formatting

- **Course Information**: Create a two-column table with Field and Details headers
- **Instructional Hours**: Use tables for structured numeric data
- **Mapping Tables**: Preserve CO-PSO and CO-PO mapping in tabular format with proper alignment
- Use `|` separators and proper alignment
- Bold headers using `**text**` within table cells

### Content Organization

1. **Course Details**: Present in structured table format with clear field labels
2. **Objectives**: Use bullet points with `-` for multi-point objectives
3. **Course Outline**: 
   - Organize by units using `###` headers
   - Use `####` for topic subdivisions
   - Present content in logical bullet point lists
4. **Learning Outcomes**: Use `**CO1**`, `**CO2**` format for course outcome labels
5. **References**: Use numbered lists for textbooks and reference books

### Text Formatting Rules

- **Bold**: Use for important labels, course codes, and outcome identifiers
- **Italic**: Use sparingly, only for book titles using `*text*`
- **Chemical Formulas**: Present as subscript when possible (CH₄, C₂H₄)
- **Lists**: Use `-` for unordered lists, `1.` for ordered lists
- **Emphasis**: Bold key terms and section identifiers

### Citation and Source Management

- Add `[attached_file:1]` citations at the end of each major section
- Maintain original content accuracy while improving readability
- Preserve all technical terms, course codes, and academic terminology exactly

### Special Elements

- **Horizontal Rules**: Use `---` to separate major document sections
- **University Information**: Place at bottom in standard format
- **Tables**: Ensure proper column alignment and header formatting
- **Code/Formulas**: Use inline code format when appropriate

### Quality Standards

- Maintain academic tone and precision
- Ensure all numerical data, codes, and technical terms are preserved exactly
- Create clear visual hierarchy through consistent heading structure
- Use tables for comparative or structured data presentation
- Preserve original document's logical flow and organization
"""